version: "3"

services:
  backend:
    container_name: product-backend
    image: product-backend:latest
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080

  frontend:
    container_name: product-frontend
    image: "product-frontend:latest"
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "4200:4200"

  db:
    image: "postgres:13.1-alpine"
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
